project:
  type: website
website:
  title: "Ben R Woodard's Blog"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - about.qmd
      - text: "adobeanalyticsr"
        href: https://adobeanalyticsr.com
        target: _blank
      - text: "cjar"
        href: https://benrwoodard.github.io/cjar/
        target: _blank
      - icon: github
        href: https://github.com/benrwoodard
      - icon: linkedin
        href: https://www.linkedin.com/in/benrwoodard
  search: true
format:
  html:
    theme: flatly
    css: styles.css
    template-partials:
      - "_quarto/partials/title-block.html"

    
